/**
 * File Management Service for CARJAN scenarios
 * Handles saving, loading, importing and exporting of scenario files
 */

export class FileManagerService {
  constructor() {
    this.supportedFormats = ["json", "carla-python"];
    this.electronAPI = window.electronAPI;
  }

  /**
   * Show save dialog and save scenario
   */
  async saveScenarioAs(scenarioData, defaultName = "scenario") {
    if (!this.electronAPI) {
      throw new Error("File operations require Electron environment");
    }

    try {
      const result = await this.electronAPI.showSaveDialog({
        title: "Save Scenario",
        defaultPath: `${defaultName}.json`,
        filters: [
          { name: "CARJAN Scenarios", extensions: ["json"] },
          { name: "All Files", extensions: ["*"] },
        ],
      });

      if (!result.canceled && result.filePath) {
        await this.electronAPI.writeFile(
          result.filePath,
          JSON.stringify(scenarioData, null, 2)
        );
        return { success: true, filePath: result.filePath };
      }

      return { success: false, canceled: true };
    } catch (error) {
      console.error("Failed to save scenario:", error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Show open dialog and load scenario
   */
  async openScenario() {
    if (!this.electronAPI) {
      throw new Error("File operations require Electron environment");
    }

    try {
      const result = await this.electronAPI.showOpenDialog({
        title: "Open Scenario",
        filters: [
          { name: "CARJAN Scenarios", extensions: ["json"] },
          { name: "All Files", extensions: ["*"] },
        ],
        properties: ["openFile"],
      });

      if (!result.canceled && result.filePaths.length > 0) {
        const filePath = result.filePaths[0];
        const content = await this.electronAPI.readFile(filePath);
        const scenarioData = JSON.parse(content);

        return {
          success: true,
          data: scenarioData,
          filePath: filePath,
        };
      }

      return { success: false, canceled: true };
    } catch (error) {
      console.error("Failed to open scenario:", error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Export scenario in different formats
   */
  async exportScenario(scenarioData, format = "json") {
    const exportData = this.prepareExportData(scenarioData, format);

    const extension = format === "carla-python" ? "py" : "json";
    const defaultName = `${scenarioData.metadata.name.replace(
      /[^a-zA-Z0-9]/g,
      "_"
    )}_export.${extension}`;

    if (this.electronAPI) {
      return await this.saveExportFile(exportData, defaultName, format);
    } else {
      // Web fallback - download file
      this.downloadFile(exportData.content, defaultName);
      return { success: true, method: "download" };
    }
  }

  /**
   * Prepare data for export based on format
   */
  prepareExportData(scenarioData, format) {
    switch (format) {
      case "json":
        return {
          content: JSON.stringify(scenarioData, null, 2),
          mimeType: "application/json",
        };

      case "carla-python":
        return {
          content: this.generateCarlaScript(scenarioData),
          mimeType: "text/x-python",
        };

      default:
        throw new Error(`Unsupported export format: ${format}`);
    }
  }

  /**
   * Generate CARLA Python script from scenario data
   */
  generateCarlaScript(scenarioData) {
    const { metadata, environment, entities, paths, waypoints } = scenarioData;

    return `#!/usr/bin/env python3
"""
CARLA Scenario: ${metadata.name}
Generated by CARJAN-app on ${new Date().toISOString()}
Author: ${metadata.author || "Unknown"}
Description: ${metadata.description || "No description"}
"""

import carla
import random
import time
import math

class CarjanScenario:
    def __init__(self):
        self.client = None
        self.world = None
        self.blueprint_library = None
        self.spawn_points = []
        self.vehicles = []
        self.pedestrians = []
        
    def connect_to_carla(self, host='localhost', port=2000, timeout=10.0):
        """Connect to CARLA server"""
        try:
            self.client = carla.Client(host, port)
            self.client.set_timeout(timeout)
            self.world = self.client.get_world()
            self.blueprint_library = self.world.get_blueprint_library()
            self.spawn_points = self.world.get_map().get_spawn_points()
            print(f"Connected to CARLA server at {host}:{port}")
            return True
        except Exception as e:
            print(f"Failed to connect to CARLA: {e}")
            return False
    
    def setup_environment(self):
        """Setup weather and environment settings"""
        weather = carla.WeatherParameters(
            cloudiness=${this.getWeatherValue(
              environment.weather,
              "cloudiness"
            )},
            precipitation=${this.getWeatherValue(
              environment.weather,
              "precipitation"
            )},
            precipitation_deposits=${this.getWeatherValue(
              environment.weather,
              "precipitation_deposits"
            )},
            wind_intensity=${this.getWeatherValue(
              environment.weather,
              "wind_intensity"
            )},
            sun_azimuth_angle=${this.getWeatherValue(
              environment.weather,
              "sun_azimuth_angle"
            )},
            sun_altitude_angle=${this.getWeatherValue(
              environment.weather,
              "sun_altitude_angle"
            )}
        )
        self.world.set_weather(weather)
        print(f"Weather set to: ${environment.weather}")
    
    def spawn_entities(self):
        """Spawn all entities from scenario"""
        ${this.generateEntitySpawnCode(entities)}
    
    def create_paths(self):
        """Create and visualize paths"""
        ${this.generatePathCode(paths, waypoints)}
    
    def run_scenario(self):
        """Main scenario execution"""
        if not self.connect_to_carla():
            return False
            
        try:
            self.setup_environment()
            self.spawn_entities()
            self.create_paths()
            
            print("Scenario setup complete!")
            print("Press Ctrl+C to stop...")
            
            # Keep scenario running
            while True:
                time.sleep(1.0)
                
        except KeyboardInterrupt:
            print("Stopping scenario...")
        except Exception as e:
            print(f"Scenario error: {e}")
        finally:
            self.cleanup()
    
    def cleanup(self):
        """Clean up spawned actors"""
        for vehicle in self.vehicles:
            if vehicle.is_alive:
                vehicle.destroy()
        for pedestrian in self.pedestrians:
            if pedestrian.is_alive:
                pedestrian.destroy()
        print("Cleanup complete")

# Scenario data (for reference)
SCENARIO_DATA = ${JSON.stringify(scenarioData, null, 4)}

if __name__ == "__main__":
    scenario = CarjanScenario()
    scenario.run_scenario()
`;
  }

  /**
   * Generate entity spawn code for CARLA script
   */
  generateEntitySpawnCode(entities) {
    if (!entities || entities.length === 0) {
      return "        # No entities to spawn";
    }

    return entities
      .map((entity, index) => {
        const { type, x, y, heading } = entity;

        switch (type) {
          case "vehicle":
            return `        # Spawn vehicle at grid position (${x}, ${y})
        vehicle_bp = random.choice(self.blueprint_library.filter('vehicle.*'))
        if len(self.spawn_points) > ${index}:
            spawn_point = self.spawn_points[${index}]
            vehicle = self.world.spawn_actor(vehicle_bp, spawn_point)
            self.vehicles.append(vehicle)
            print(f"Spawned vehicle at {spawn_point.location}")`;

          case "pedestrian":
            return `        # Spawn pedestrian at grid position (${x}, ${y})
        pedestrian_bp = random.choice(self.blueprint_library.filter('walker.pedestrian.*'))
        if len(self.spawn_points) > ${index}:
            spawn_point = self.spawn_points[${index}]
            pedestrian = self.world.spawn_actor(pedestrian_bp, spawn_point)
            self.pedestrians.append(pedestrian)
            print(f"Spawned pedestrian at {spawn_point.location}")`;

          default:
            return `        # Entity type '${type}' not implemented`;
        }
      })
      .join("\n\n");
  }

  /**
   * Generate path code for CARLA script
   */
  generatePathCode(paths, waypoints) {
    if (!paths || paths.length === 0) {
      return "        # No paths to create";
    }

    return `        # Create debug visualization for paths
        debug = self.world.debug
        
        ${paths
          .map(
            (path, index) => `
        # Path ${index + 1}: ${path.id || "Unnamed"}
        path_waypoints = [
            ${
              path.waypoints
                ?.map(
                  (wp) => `carla.Location(x=${wp.x * 4}, y=${wp.y * 4}, z=0.5)`
                )
                .join(",\n            ") || ""
            }
        ]
        
        for i in range(len(path_waypoints) - 1):
            debug.draw_line(
                path_waypoints[i],
                path_waypoints[i + 1],
                thickness=0.1,
                color=carla.Color(33, 150, 243),  # Blue
                life_time=0  # Permanent
            )
        `
          )
          .join("\n")}`;
  }

  /**
   * Get weather parameter values
   */
  getWeatherValue(weather, parameter) {
    const weatherMap = {
      Clear: {
        cloudiness: 0,
        precipitation: 0,
        precipitation_deposits: 0,
        wind_intensity: 0,
        sun_azimuth_angle: 0,
        sun_altitude_angle: 75,
      },
      Cloudy: {
        cloudiness: 80,
        precipitation: 0,
        precipitation_deposits: 0,
        wind_intensity: 10,
        sun_azimuth_angle: 0,
        sun_altitude_angle: 45,
      },
      Rainy: {
        cloudiness: 90,
        precipitation: 90,
        precipitation_deposits: 90,
        wind_intensity: 30,
        sun_azimuth_angle: 0,
        sun_altitude_angle: 30,
      },
    };

    return weatherMap[weather]?.[parameter] || 0;
  }

  /**
   * Save export file using Electron
   */
  async saveExportFile(exportData, defaultName, format) {
    const filters =
      format === "carla-python"
        ? [{ name: "Python Scripts", extensions: ["py"] }]
        : [{ name: "JSON Files", extensions: ["json"] }];

    try {
      const result = await this.electronAPI.showSaveDialog({
        title: `Export Scenario (${format})`,
        defaultPath: defaultName,
        filters: [...filters, { name: "All Files", extensions: ["*"] }],
      });

      if (!result.canceled && result.filePath) {
        await this.electronAPI.writeFile(result.filePath, exportData.content);
        return { success: true, filePath: result.filePath };
      }

      return { success: false, canceled: true };
    } catch (error) {
      console.error("Failed to export scenario:", error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Download file in browser (web fallback)
   */
  downloadFile(content, fileName) {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  /**
   * Auto-save to localStorage
   */
  autoSaveToLocal(scenarioData, key = "carjan_autosave") {
    try {
      const saveData = {
        timestamp: new Date().toISOString(),
        data: scenarioData,
      };
      localStorage.setItem(key, JSON.stringify(saveData));
      return true;
    } catch (error) {
      console.error("Auto-save failed:", error);
      return false;
    }
  }

  /**
   * Load auto-save from localStorage
   */
  loadAutoSave(key = "carjan_autosave") {
    try {
      const saveData = localStorage.getItem(key);
      if (saveData) {
        const parsed = JSON.parse(saveData);
        return {
          success: true,
          data: parsed.data,
          timestamp: parsed.timestamp,
        };
      }
      return { success: false, reason: "No auto-save found" };
    } catch (error) {
      console.error("Failed to load auto-save:", error);
      return { success: false, error: error.message };
    }
  }
}

export const fileManager = new FileManagerService();
